
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

import model.Greeting;

public class GreetingTest {
	@Test
	public void testGetDBObject() {
		 assertNotNull("getDBObject should return DBObject", Greeting.getDBObject(new Greeting("exampleid", "greeting")));
	}
}
